'use strict';

const fs = require('node:fs');
const path = require('node:path');

const REPO_ROOT = path.resolve(__dirname, '..');
const ICONS_DIR = path.join(REPO_ROOT, 'assets', 'icons');
const OUTPUT_FILE = path.join(REPO_ROOT, 'public', 'js', 'generated_icons.js');

function normalizeSvgSource(svgSource) {
  return String(svgSource || '')
    .replace(/\r\n/g, '\n')
    .trim();
}

function collectCanonicalIcons(iconsDir = ICONS_DIR) {
  const fileNames = fs.readdirSync(iconsDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && path.extname(entry.name).toLowerCase() === '.svg')
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const icons = {};
  fileNames.forEach((fileName) => {
    const iconName = path.basename(fileName, '.svg');
    const absolutePath = path.join(iconsDir, fileName);
    const svgMarkup = normalizeSvgSource(fs.readFileSync(absolutePath, 'utf8'));
    icons[iconName] = svgMarkup;
  });

  return {
    iconNames: fileNames.map((fileName) => path.basename(fileName, '.svg')),
    icons,
  };
}

function buildGeneratedRegistrySource({
  sourceDir = 'assets/icons',
  iconNames,
  icons,
} = {}) {
  if (!Array.isArray(iconNames)) {
    throw new Error('buildGeneratedRegistrySource requires iconNames');
  }
  if (!icons || typeof icons !== 'object') {
    throw new Error('buildGeneratedRegistrySource requires icons');
  }

  const iconNamesJson = JSON.stringify(iconNames, null, 2);
  const iconsJson = JSON.stringify(icons, null, 2);

  return `// public/js/generated_icons.js
'use strict';

// Auto-generated by tools/generate_renderer_icons.js from ${sourceDir}.
// Do not edit by hand; regenerate with \`npm run generate:icons\`.

(() => {
  const registry = {
    sourceDir: ${JSON.stringify(sourceDir)},
    iconNames: Object.freeze(${iconNamesJson}),
    icons: Object.freeze(${iconsJson}),
  };

  window.GeneratedRendererIcons = Object.freeze(registry);
})();
`;
}

function generateRendererIconsFile({
  iconsDir = ICONS_DIR,
  outputFile = OUTPUT_FILE,
  sourceDir = 'assets/icons',
} = {}) {
  const { iconNames, icons } = collectCanonicalIcons(iconsDir);
  const fileSource = buildGeneratedRegistrySource({
    sourceDir,
    iconNames,
    icons,
  });
  fs.writeFileSync(outputFile, fileSource, 'utf8');
  return {
    outputFile,
    iconNames,
    fileSource,
  };
}

if (require.main === module) {
  const result = generateRendererIconsFile();
  process.stdout.write(
    `Generated ${path.relative(REPO_ROOT, result.outputFile)} from ${result.iconNames.length} canonical icons.\n`
  );
}

module.exports = {
  ICONS_DIR,
  OUTPUT_FILE,
  buildGeneratedRegistrySource,
  collectCanonicalIcons,
  generateRendererIconsFile,
  normalizeSvgSource,
};
